# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  # name of the job is backend
  backend:
    jobs:
      - python_install
      - linting:
          requires:
            - python_install
      - django_checks:
          requires:
            - python_install
      - django_unittests:
          requires:
            - python_install
      - selenium_tests:
          requires:
            - python_install


################################################################################
commands:
  python_install:
    description: |
      install python dependencies
    steps:
    - run: 
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements39.txt
  linting:
    steps:
    - run:
        command: |
          . ./venv/bin/activate
          black --line-length 117 --exclude '^.*\b(migrations)\b.*$' --check django_backend selenium_tests
  django_checks:
    steps:
    - run:
        command: |
          . ../venv/bin/activate
          python3 manage.py check --settings=gradia_stocker.settings_dev
          python3 manage.py collectstatic --settings=gradia_stocker.settings_dev
          python3 manage.py migrate --settings=gradia_stocker.settings_dev
        working_directory: django_backend
  django_unittests:
    steps:
    - run:
        command: |
          . ../venv/bin/activate
          python3 manage.py test --settings=gradia_stocker.settings_dev
        working_directory: django_backend
  selenium_tests:
    steps:
    - run:
        command: PATH=$PATH:. chromedriver --version
        working_directory: selenium_tests
    - run:
        command: |
          . ../venv/bin/activate
          PATH=$PATH:. pytest
        working_directory: selenium_tests

################################################################################
executors:
  python_environment:
    description: |
      Python Django runtime environment
    docker:
    - image: circleci/python:<<parameters.python>>-browsers
    parameters:
      python:
        default: "3.9"
        type: string
################################################################################
jobs:
  python_install:
    executor: python_environment
    parameters:
      before_install:
        default:
        - checkout
        type: steps
    steps:
    - steps: <<parameters.before_install>>
    - restore_cache:
        key: deps1-{{ .Branch }}-{{ checksum "requirements39.txt" }}
    - python_install
    - persist_to_workspace:
        paths:
        - project
        root: ~/
    - save_cache:
        key: deps1-{{ .Branch }}-{{ checksum "requirements39.txt" }}
        paths:
        - "venv"
  linting:
    executor: python_environment
    steps:
    - attach_workspace:
        at: ~/
    - linting
    - store_test_results:
        path: reports/linting
    - store_artifacts:
        path: test-reports/
        destination: python_app
  django_checks:
    executor: python_environment
    steps:
    - attach_workspace:
        at: ~/
    - django_checks
    - store_test_results:
        path: reports/django_checks
    - store_artifacts:
        path: test-reports/
        destination: python_app
  django_unittests:
    executor: python_environment
    steps:
    - attach_workspace:
        at: ~/
    - django_unittests
    - store_test_results:
        path: reports/django_unittests
    - store_artifacts:
        path: test-reports/
        destination: python_app
  selenium_tests:
    executor: python_environment
    steps:
    - attach_workspace:
        at: ~/
    - selenium_tests
    - store_test_results:
        path: reports/selenium_tests
    - store_artifacts:
        path: test-reports/
        destination: python_app

################################################################################
