name: Test Cases
on: [push]
jobs:
  dependency_install:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up testing environment and install dependencies!!!"
      - run: echo "This is where we are going to install our dependencies"
  django_unittests:
    needs: dependency_install
    steps:
      - run: echo "This is where we run our unittests"
  linting:
    steps:
      - run: echo "This is where we run our black and js linter"
  selenium_tests:
    steps:
      - run: echo "We run selenium tests here"
