name: Test Cases
on: [push]
jobs:
  dependency_install:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up testing environment and install dependencies!!!"
      - run: echo "install python and javascript dependencies"
      - run: |
          sudo apt-get update 
          python3 -m venv venv
          sudo apt-get install -y latexmk texlive-latex-extra
          sudo apt-get install fonts-freefont-ttf
          pip uninstall stone-grading -y
          pip install -r requirements39.txt
          pip install git+https://github.com/gradia-exchange/StoneGrading
          pwd
          ls
          cd frontend
          npm install
          CI=false npm run build
      - 
  django_unittests:
    runs-on: ubuntu-latest
    needs: dependency_install
    steps:
      - run: echo "This is where we run our unittests"
  linting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is where we run our black and js linter"
  selenium_tests:
    runs-on: ubuntu-latest
    needs: dependency_install
    steps:
      - run: echo "We run selenium tests here"
