name: Test Cases
on: [push]
jobs:
  dependency_install:
    runs-on: ubuntu-latest
    name: Check out repository
    uses: actions/checkout@v2
    name: Set up Node.js
    with:
      node-version 14
    steps:
      - run: echo "Setting up testing environment and install dependencies!!!"
      - run: echo "install python and javascript dependencies"
      - run: |
          sudo apt-get update 
          python3 -m venv venv
          sudo apt-get install -y latexmk texlive-latex-extra
          sudo apt-get install fonts-freefont-ttf
          pwd
          ls
          cd frontend
          pip install git+https://github.com/gradia-exchange/StoneGrading
          npm install
          CI=false npm run build
  django_unittests:
    runs-on: ubuntu-latest
    needs: dependency_install
    steps:
      - run: echo "running django unittests..."
      - run: |
          . venv/bin/activate
          cd django_backend && pytest
  linting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running linting..."
      - run: |
          black --line-length 117 --exclude '^.*\b(migrations)\b.*$' --check django_backend selenium_tests
          flake8 --config flake8-config django_backend selenium_tests
          cd frontend && npm run lint
  django_checks:
    needs: dependency_install
    runs-on: ubuntu-latest
    steps:
      - run: |
          . venv/bin/activate
          cd django_backend
          python manage.py check --settings=gradia_lab.settings_dev
          python manage.py collectstatic --settings=gradia_lab.settings_dev
          python manage.py loadfixtures --settings=gradia_lab.settings_dev
  selenium_tests:
    runs-on: ubuntu-latest
    needs: dependency_install
    steps:
      - run: echo "Running selenium tests..."
      - run: |
          . venv/bin/activate
          cd selenium_tests
          pytest
